### ISSUE TITLE
Using financial_pdf_parsing with beancount-import

### ISSUE THREAD

**Issue by catanzaromj** [m-d-brown/plain-text-accounting-tools#1]
Hey thanks for writing this awesome set of scripts! I've found the financial_pdf_parsing oen very useful. The output file (`update.bean` in your README) consists of transactions with only a single account. Is there a way to pass this off to beancount-import so I don't have to manually add the other account for each transaction? Would the best way to go about this be to write a custom beancount importer? If so, have you done this already? Thanks for this, I'm new to PTA.

P.S. The link to beancount-basics on your README is dead.

**Comment by m-d-brown** [comment]
Thanks for the feedback! Yes, there's an easy way to integrate this with beancount-import via an importer it provides that wraps standard beancount import implementations. I'll update the README to describe that.

Thanks for pointing out the dangling link to beancount-basisc as well. I didn't finish the overview so I dropped it. The references in the first paragraph of the README are better ways to get started with PTA.

**Comment by catanzaromj** [comment]
Thanks for the updates. Works great!
