### ISSUE TITLE
BofA checking account missing transactions with beancount-import

### ISSUE THREAD

**Issue by catanzaromj** [m-d-brown/plain-text-accounting-tools#2]
I'm not sure if there is an easy way to describe the issue I'm having. I have a BofA checking account with multiple transactions on each statement. When I use the first method in the readme (`import.py`), I see all the transactions in `update.bean` as expected, including the balance assertions. When I use the beancount-import method of the readme, only the first transaction on each statement is imported. The balance assertion is also missing (although maybe it is supposed to be with this method). I'm also not sure how to use pytest to check this second approach.

**Comment by catanzaromj** [comment]
I re-downloaded the statement from BofA and everything works fine now. I'm not sure what happened.

**Comment by m-d-brown** [comment]
Glad to hear you got this working! If it reoccurs, let me know and try to provide some input that replicates the problem, and I'll try to fix it.
